[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Optional: set a base directory if your repo root isn't the site root
# [build.environment]
#   NODE_VERSION = "16"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
